### ISSUE TITLE
UnicodeDecode Error

### ISSUE THREAD

**Issue by amritkrs** [Alir3z4/html2text#53] opened 2015-01-08 09:22 UTC
r = requests.get("http://en.wikipedia.org/wiki/Python_%28programming_language%29")
print html2text.html2text(r.content)

Traceback (most recent call last):
File "", line 1, in
File "html2text/init.py", line 750, in html2text
return h.handle(html)
File "html2text/init.py", line 121, in handle
return self.optwrap(self.close())
File "html2text/init.py", line 139, in close
outtext = nochr.join(self.outtextlist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 62: ordinal not in range(128)

**Comment by Alir3z4** [comment] 2015-01-08 09:23
duplicate of #47

**Closed by Alir3z4** 2015-01-08 09:23 UTC
Labels: duplicate

**Comment by amritkrs** [comment] 2015-01-08 09:28
sorry,i was asked to post here from https://github.com/aaronsw/html2text/issues/96#issuecomment-69016416.
i should have checked!

**Comment by Alir3z4** [comment] 2015-01-08 09:40
@amritkrs no problem.
in the issue #47 the word around is also mentioned which is a SO answer.

patches are welcome as well.

**Comment by Alir3z4** [comment] 2015-01-08 09:47
@mcepl thank you to guide user to this repo ;)

**Comment by amritkrs** [comment] 2015-01-08 10:12
Thank you guys for all your help,its working nicely!

**Comment by mcepl** [comment] 2015-01-08 11:07
> @mcepl thank you to guide user to this repo ;)

That was meant seriously or ironically? Anyway, Happy New Year!

**Comment by Alir3z4** [comment] 2015-01-08 11:13
@mcepl Of course I meant it and serious. Happy New Year to you too, wish you have a greatest one ;)
