### ISSUE TITLE
html2text inserts newline in URLs

### ISSUE THREAD

**Issue by amitu** [Alir3z4/html2text#127] opened 2016-05-24 16:16 UTC
- Version: 2016.4.2
- Python 2.7.11

``` python
>>> html2text.html2text('<img src="http://www.foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.com">')
u'![](http://www.foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\noooooooooooooooooooooooooooooooooooooooooooooooo.com)\n\n'
```

Been fixing in my code:

``` python
BRACKET_RE = re.compile(r"\((.*?)\)", re.MULTILINE|re.DOTALL)

def replace_newlines_in_links(match):
    match = match.group()
    match = match.replace("\n", "")
    return match


def html2md(text):
    text = html2text.html2text(text)
    text = re.sub(BRACKET_RE, replace_newlines_in_links, text)
    return text
```

**Comment by theSage21** [comment] 2016-05-24 16:47
The body width is enforced post conversion so I don't see a way to exclusively make links unbroken without some hacky changes. @Alir3z4 do you? @amitu Meanwhile if you want you could try to do something like:

    >>> html2text.html2text('<img src="http://www.foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.com">', bodywidth=0)
    u'![](http://www.foooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.com)\n'

In case your links are all in a similar format.

**Comment by Alir3z4** [comment] 2016-05-24 19:09
In my opinion this is not a bug, it has been opened bunch of other times before as well.
`bodywidth=0` is the way to go without making any changes in the code.

@theSage21 Do you think it would be a good idea to remove this behavior ?

**Comment by theSage21** [comment] 2016-05-25 02:45
I don't know. If someone +1s this then sure.

**Comment by amitu** [comment] 2016-05-25 04:13
But I like neatly wrapped paragraphs. Markdown text is for human consumption.

**Comment by amitu** [comment] 2016-05-25 04:57
I believe even `break_on_hyphens=False` should be used but it breaks existing test. That test in my opinion is asserting a bug and should be removed (along with config.PROTECT_LINKS and config.WRAP_LINKS "features" in favour of this). 

Breaking links == BUG and should not be allowed under any circumstance.

**Comment by amitu** [comment] 2016-05-25 05:08
There may be situations where you would care more about presentation than correctness, e.g. if you are printing the markdown to a book/pdf.

I still feel default behaviour should be to not break links, but **if backward compatibility is a concern** for merging my pull request we can add `break_on_hyphens=True` and `break_long_words=True` keyword arguments/config parameters.

**Comment by theSage21** [comment] 2016-05-25 06:40
Sounds resonable. I'll do this once my exams are done. Sigh, so many issues are await me once I've completed my exams. :smile: Also, @amitu #128 is welcome. I did not know about that.

**Comment by amitu** [comment] 2016-05-25 08:04
You are welcome. In the meanwhile this is what I am using:

```python
def html2md(text):
    text = html2text.html2text(text, bodywidth=0)
    text = textwrap.wrap(text, break_long_words=False, break_on_hyphens=False)
    return text
```

It may be we do not need #128 :-p.

**Comment by amitu** [comment] 2016-05-28 05:58
Hey @theSage21, thanks for merging the pull request.

What do we do about `break_on_hyphens=True`? If a URL has hyphens in it, it will still break.

I have not added break_on_hyphens in my pull request as that was breaking an existing test (protect_links.md). That test in my opinion is wrong, it is asserting a behaviour that is a bug. 

Should I remove the test and send another pull request?

**Comment by theSage21** [comment] 2016-05-28 07:26
Could you explain this buggy behaviour? Changing that might break backward compatibility for some people and so we need to be sure that it's the right change.

**Comment by amitu** [comment] 2016-05-28 08:08
The same as this issue:

protect_links.html

```html
<a href="http://im-a-very-very-very-very-very-very-very-very-very-very-long/link.html">foo</a>
```

protect_links.md
```
[foo](<http://im-a-very-very-very-very-very-very-very-very-very-very-
long/link.html>)

```

As you can see it is doing the *opposite* of protecting. 

If we replace - with anything else, e.g. _, then it will not insert the line break. This behaviour that sometimes the links will 404, is a bug. 

In order to handle backward compatibility we can make this an optional keyword argument. 

What should be the default value? `break_on_hyphens=True`? If so new comers of this library should be warned. If `break_on_hyphens=False` then current users should be cautioned.

I feel since the issue is "serious", it leads to links breaking inadvertently, nobody wants that, so default should be False. 

You take a call :-)

**Comment by theSage21** [comment] 2016-05-28 08:32
I'd say we change the tests and put it in the Changelog.   @Alir3z4 ?

**Comment by Alir3z4** [comment] 2016-05-28 10:37
This:
protect_links.html

```html
<a href="http://im-a-very-very-very-very-very-very-very-very-very-very-long/link.html">foo</a>
```

protect_links.md
```
[foo](<http://im-a-very-very-very-very-very-very-very-very-very-very-
long/link.html>)

```

is kind of wrong when it's default, I'm not sure why the default behavior is like this.
I disagree to remove it as well.

Let's change it to be by default and have the this current behavior as an option as well.

So I suggest the steps to change it to be:

* Add a flag to do the same. Both backward compatibility and flexibility solution.
* Change the test and update the ChangeLog.rst.
* Update the docs about the new flag.
* Update the CLI about the flag.
 

That would be pretty much it.

**Comment by amitu** [comment] 2016-05-30 10:15
I will work on a pull request.

**Comment by luckydonald** [comment] 2016-07-01 09:21
Happening here too.
```python
# Python 3.4.3 (default, Aug 10 2015, 16:40:44) 
# [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
>>> import html2text
>>> html2text.__version__
(2016, 4, 2)

>>> # html -> markdown preset
>>> txt = html2text.HTML2Text()
>>> txt.single_line_break = True
>>> txt.ignore_tables = True
>>> txt.ignore_anchors = True
>>> txt.images_to_alt = True
>>> txt.ignore_images = True
>>> txt.emphasis_mark = '_'
>>> txt.escape_snob = True
>>> txt.strong_mark = '*'

>>> txt.handle("""Go find that below!<br><br><br><a href="http://www.equestriadaily.com/2016/06/ponykart-inspired-pony-kart-racer-in.html#more">Read more »</a><img src="http://feeds.feedburner.com/~r/EquestriaDaily/~4/MkwLIXil3iI" height="1" width="1" alt=""/>""")
'Go find that below\\!  \n  \n  \n[Read more »](http://www.equestriadaily.com/2016/06/ponykart-inspired-pony-\nkart-racer-in.html#more)\n\n'

Note, the workaround in https://github.com/Alir3z4/html2text/issues/127#issuecomment-221372620  (setting `bodywidth=0` is named different inside the class:
```python
txt = HTML2Text(bodywidth=0)
txt.body_width = 0
```

**Comment by amitu** [comment] 2016-07-02 14:30
Haven't gotten time to work on it. @luckydonald, you can pass `break_on_hyphens=True` and check if it works. [Refer](https://github.com/Alir3z4/html2text/pull/128/files#diff-5e3a9e55d540708ee71bbae0911b45bbR818).

**Comment by luckydonald** [comment] 2016-07-02 19:06
I went with
```python
txt.body_width = 0
```

**Comment by Alir3z4** [comment] 2024-01-16 17:25
Closing as https://github.com/Alir3z4/html2text/issues/127#issuecomment-230117125 seems to be a good workaround unless _(until)_ we come up with a better implementation _(if needed)._

**Closed by Alir3z4** 2024-01-16 17:25 UTC
