### ISSUE TITLE
Two extra spaces added before line breaks

### ISSUE THREAD

**Issue by sirdodger** [Alir3z4/html2text#91] opened 2015-08-21 18:24 UTC
Whitespace in HTML should be ignored, but the parser seems to add extra spaces before a newline when translating a &lt;br&gt;.

```
>>> import html2text
>>> html2text.__version__
(2015, 6, 21)
>>> p = html2text.HTML2Text(bodywidth=0)
>>> p.handle('foo<br>bar')
u'foo  \nbar\n'
```

In addition to the two spaces added, it preserves one extra space, if present.  (Though that seems sane to me, to treat any length of whitespace in html as a single space in text.)

```
>>> p.handle('foo   <br>    bar')
u'foo   \nbar\n'
```

It is a low impact problem in practice, but it makes automated testing a bit of a hassle.

Is there a reason for the extra spaces?  The parser is very explicit on the replace:

```
        if tag == "br" and start:
            self.o("  \n")
```

**Comment by Alir3z4** [comment] 2015-10-17 15:00
I'm not really sure the design decision behind having that extra space. 
@theSage21 any idea?

@sirdodger If no specific reason is behind this, a flag is welcome to switch this thing off explicitly

**Comment by theSage21** [comment] 2015-10-17 19:28
After some digging I found that this particular line of code was written at <https://github.com/aaronsw/html2text/commit/7a327b84a6bb20ac5055b1c0c1219d92fde316ce>. Since he has passed away, and this was an initial commit, I cannot comment on the purpose of this code.

We can safely do away with this though it is notewhile to remember that some tests fail on changing this behaviour. In my opinion we should correct this completely without leaving a flag or so which will only bloat the codebase.

To support the last decision, since this has gone unreported for so long chances of people being affected by it are relatively low. When we change this, the worst that happens is that their tests fail, and changelog can mention that this is to be expected.

@Alir3z4 @sirdodger sound ok?

**Comment by Alir3z4** [comment] 2015-10-18 10:16
From my point of view I can't figure out the reason for this behavior.
If others also can't find a reasonable design decision behind this then my vote would go for having a flag to switch it off and remove the extra spaces from the output, which means no one's tests will fail since the default will be having the two extra spaces and the flag would be to switch this behavior.

**Comment by theSage21** [comment] 2015-10-18 14:43
@Alir3z4 @sirdodger If I remember correctly, two spaces at the end of a line specify a new line in Markdown. This is in github too I think.

```
This is line 1.
This is line 2.
There are two spaces at the end of this line.  
This is line 4.
```


This is line 1.
This is line 2.
There are two spaces at the end of this line.  
This is line 4.

Maybe we should let this be? It is a feature of Markdown after all.

**Comment by Alir3z4** [comment] 2015-10-18 18:00
Yes `<br>` is 2 spaces in markdown.
That's correct, what I was thinking.

The issue is closed and marked as invalid.

**Closed by Alir3z4** 2015-10-18 18:00 UTC

**Comment by sirdodger** [comment] 2015-10-20 23:13
Thanks for the clarification!
