### ISSUE TITLE
Table padding crash on empty tables

### ISSUE THREAD

**Issue by cgianlu** [Alir3z4/html2text#320] opened 2020-04-23 15:11 UTC
reformat_table function raise an exception in case of empty tables (i.e. \<table\>\<\/table\>).

In fact in this case the list passed as parameter (lines) is empty so the following statement is wrong (lines[0] does not exist!)

                  max_width = [len(x.rstrip()) + right_margin for x in lines[0].split("|")]

**Comment by mpodolsk** [comment] 2021-06-01 13:15
any plans to patch this issue, looks simple enough?

**Comment by mpodolsk** [comment] 2021-06-08 11:08
the issue is also present when the <tr> does not have corresponding </tr>.
closing the <tr> is optional.
this issue is present because whole table is treated as one line and the </special_marker_for_table_padding> is in that line

I will workup a fork.

**Comment by Alir3z4** [comment] 2021-06-12 08:46
Fixed in https://github.com/Alir3z4/html2text/pull/361

**Closed by Alir3z4** 2021-06-12 08:46 UTC

**Comment by mpodolsk** [comment] 2021-06-16 16:34
when this will be tagged and published as a release ?
looking at repo tags there are some tags missing comparing to change-log notes.
latest points to 2019
