### ISSUE TITLE
HTMl enities get out of anchor text

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/html2text#31] opened 2014-10-04 00:08 UTC
@szepeviktor:

another strange behaviour
```html
<a href="http://thth" class="nolink" style="text-decoration:none;color:inherit;cursor:default;">&#225;ll&#225;s: Country Manager</a>
```
```markdown
a[llas: Country Manager](http://thth)
```

**Comment by theSage21** [comment] 2015-06-14 05:28
This is only caused when the link text begins with a char reference.
`<a href="http://thth">&#225;ll&#225;s: Country Manager</a>` causes the bug.
`<a href="http://thth"> &#225;ll&#225;s: Country Manager</a>` translates correctly to
`[ állás: Country Manager](http://thth)`

This is because the first call is to `handle_charref` and after that `handle_data` and `handle_data` is the function that adds the '['.

Fixed in #77

**Comment by theSage21** [comment] 2015-06-14 08:45
The issue is solved in #77. Can we close this?

**Comment by szepeviktor** [comment] 2015-06-14 08:50
Please wait till I get home, and confirm.

**Comment by theSage21** [comment] 2015-06-14 11:07
@szepeviktor sure sure. it is morning again and I have to sleep. See you on the other side of the sun. :smile:

**Comment by szepeviktor** [comment] 2015-06-14 23:01
There is a problem:
```
$ echo $LANG
en_US.UTF-8
$ echo '<a href="http://thth" class="nolink" style="text-decoration:none;color:inherit;cursor:default;">&#225;ll&#225;s: Country Manager</a>'| ./html2text
[allas: Country Manager](http://thth)
```
Shouldn't `&#225;` be `á`?

**Comment by theSage21** [comment] 2015-06-15 02:15
@szepeviktor The command line by default works with ASCII. Hence they are being converted to ASCII equivalents. As of now there is no command line option for `unicode`. Try this.
```
>>>import html2text as h2t
>>>H2T = h2t.HTML2Text()
>>>html = '<a href="http://thth" class="nolink" style="text-decoration:none;color:inherit;cursor:default;">&#225;ll&#225;s: Country Manager</a>'
>>>md_ascii = H2T.handle(html)
>>>H2T.unicode_snob = True
>>>md_unicode = H2T.handle(html)
>>>print(md_ascii)
[allas: Country Manager](http://thth)


>>>print(md_unicode)
[állás: Country Manager](http://thth)


>>>
```

**Comment by szepeviktor** [comment] 2015-06-15 22:21
Thank you.
Please merge #77.

**Closed** 2015-06-16 05:10 UTC
Labels: bug
