### ISSUE TITLE
3.200.3 vs 2014.7.3 output quirks

### ISSUE THREAD

**Issue by max-arnold** [Alir3z4/html2text#24] opened 2014-07-12 06:31 UTC
Just upgraded from 3.200.3 to 2014.7.3 and noticed the following things:

### Bold text inside links
```
<a href="link.htm"><b>Text</b></a>
```

Before: `[**Text**](link.htm)`
After: `**[Text**](link.htm)` (to me this looks incorrect)

### Image links
```
<a href="images/image.jpg"><img alt="Title" src="images/thumbnails/image.jpg"></img></a>
```

Before: `[![Title](images/thumbnails/image.jpg)](images/image.jpg)`
After: `![Title](images/thumbnails/image.jpg)`

### Literal links

Links like this `[http://example.com](http://example.com)` now look like this `<http://example.com>`. Is that valid markdown?

### Escapes

A lot of unnecessary escapes:  `\--`, `1\.`

Downgraded back to 3.200.3

**Comment by theSage21** [comment] 2015-06-04 04:28
I cannot reproduce this. Close the issue if solved?

**Comment by max-arnold** [comment] 2015-06-04 06:58
Master branch, revision 0112b5fd9cc603a6e8a505789bd5869b5dab5577:

Input:

    <html><body>
    <p><a href="link.htm"><b>Text</b></a></p>
    <p><a href="images/image.jpg"><img alt="Title" src="images/thumbnails/image.jpg"></img></a></p>
    <p><a href="http://example.com">http://example.com</a></p>
    <p>1. Paragraph</p>
    </body></html>


Output:

    **[Text**](link.htm)
    
    [![Title](images/thumbnails/image.jpg)](images/image.jpg)
    
    <http://example.com>
    
    1\. Paragraph


So:

* bold text inside the link - still seems to be broken
* image link - fixed
* literal link - behavior is different, but the syntax is valid markdown
* escaping - new feature (it would be nice to optionally disable it)

Adding spaces as a workaround is problematic for me, since I do not control html source files. Theoretically I can write a preprocessor (to add necessary spaces), but this will look like ugly hack.

**Comment by theSage21** [comment] 2015-06-04 07:17
The test is passing.
Am I correct in assuming `[**text**]` is required instead of `**[text**]`?
If so then the tests are passing correctly.

![screenshot from 2015-06-04 12 43 11](https://cloud.githubusercontent.com/assets/7693265/7978832/70fec36a-0ab7-11e5-9cfc-98d9645403bf.png)

- The right shows html and expected Markdown.
- The left part shows that all tests passed.

Can someone else confirm this with the latest branch master?

**Comment by Alir3z4** [comment] 2015-06-04 08:03
@theSage21 I tested with the latest of the master, @max-arnold is right about it:
```
alir3z4@html2text:~/workspace (master) $ PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text setup.py test -v
running test
........FF..........................................
======================================================================
FAIL: test_bold_inside_link_cmd (test.test_html2text.TestHTML2Text)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/test/test_html2text.py", line 99, in test_cmd
    self.assertEqual(result, actual)
AssertionError: u'**[Text**](link.htm)\n\n[![Title](images/thumbnails/image.jpg)](images/image.j [truncated]... != u'[**Text**](link.htm)\n\n[![Title](images/thumbnails/image.jpg)](images/image.j [truncated]...
- **[Text**](link.htm)
?   -
+ [**Text**](link.htm)
? +
  
  [![Title](images/thumbnails/image.jpg)](images/image.jpg)
  
  <http://example.com>
  
- 1\. Paragraph+ 1\. Paragraph
?              +
+ 


======================================================================
FAIL: test_bold_inside_link_mod (test.test_html2text.TestHTML2Text)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/test/test_html2text.py", line 92, in test_mod
    self.assertEqual(result, actual)
AssertionError: u'**[Text**](link.htm)\n\n[![Title](images/thumbnails/image.jpg)](images/image.j [truncated]... != u'[**Text**](link.htm)\n\n[![Title](images/thumbnails/image.jpg)](images/image.j [truncated]...
- **[Text**](link.htm)
?   -
+ [**Text**](link.htm)
? +
  
  [![Title](images/thumbnails/image.jpg)](images/image.jpg)
  
  <http://example.com>
  
- 1\. Paragraph+ 1\. Paragraph
?              +
+ 


----------------------------------------------------------------------
Ran 52 tests in 2.103s

FAILED (failures=2)
alir3z4@html2text:~/workspace (master) $ 
```

**Comment by theSage21** [comment] 2015-06-04 08:10
@Alir3z4 Strange. I am unable to reproduce this. Will try after a few days when I have time.

**Comment by alawibaba** [comment] 2015-06-04 14:33
PR https://github.com/Alir3z4/html2text/pull/64 should have fixed this; just tested master on my box:

    $ git clone https://github.com/Alir3z4/html2text.git
    Cloning into 'html2text'...
    remote: Counting objects: 1389, done.
    remote: Compressing objects: 100% (92/92), done.
    remote: Total 1389 (delta 47), reused 0 (delta 0), pack-reused 1296
    Receiving objects: 100% (1389/1389), 732.22 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (717/717), done.
    Checking connectivity... done.
    $ cd html2text
    $ PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text setup.py test -v
    running test
    ..................................................
    ----------------------------------------------------------------------
    Ran 50 tests in 1.441s

    OK
    $ python
    Python 2.7.6 (default, Mar 22 2014, 22:59:56)
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import html2text
    >>> html2text.html2text('<a href="g"><b>a</b></a>')
    u'[**a**](g)\n\n'

This is against commit hash 0112b5fd9cc603a6e8a505789bd5869b5dab5577.

Can you post the details of your environment here? My testing was done under ubuntu python 2.7.6.

**Comment by Alir3z4** [comment] 2015-06-04 15:13
@alawibaba I'm on the latest as well, this is weird.
Lemme try to re-initialize the environment.

**Comment by theSage21** [comment] 2015-06-04 15:16
@alawibaba On Mint 17, python 2.7.6 and python 3.4.0 all tests pass. This is with a clean install of venv and git clone at commit 0112b5fd9cc603a6e8a505789bd5869b5dab5577

```
python
Python 3.4.0 (default, Apr 11 2014, 13:05:18) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2text
>>> html2text.html2text('<a href="g"><b>a</b></a>')
'[**a**](g)\n\n'
>>> 
```

and 


```
python
Python 2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2text
>>> html2text.html2text('<a href="g"><b>a</b></a>')
u'[**a**](g)\n\n'
>>> 
```

**Comment by Alir3z4** [comment] 2015-06-04 15:21
@alawibaba @max-arnold @theSage21 I confirm `**[Text**](link.htm)` doesn't happen:

input:
```
<html><body>
<p><a href="link.htm"><b>Text</b></a></p>
<p><a href="images/image.jpg"><img alt="Title" src="images/thumbnails/image.jpg"></img></a></p>
<p><a href="http://example.com">http://example.com</a></p>
<p>1. Paragraph</p>
</body></html>
```
output:
```
[**Text**](link.htm)

[![Title](images/thumbnails/image.jpg)](images/image.jpg)

<http://example.com>

1\. Paragraph


```

I'll create new tests in a minute.

I'm so happy this issue is going to be closed.

**Comment by Alir3z4** [comment] 2015-06-04 15:45
Yep, this issue can be closed.

**Comment by alawibaba** [comment] 2015-06-04 20:10
:+1: Glad to see this closed!

**Comment by max-arnold** [comment] 2015-06-05 03:52
Works for me too, thanks a lot! Any plans for next release?

**Comment by Alir3z4** [comment] 2015-06-05 07:46
New release https://pypi.python.org/pypi/html2text/2015.6.6 ;)

**Closed by Alir3z4** 2015-06-05 07:46 UTC
Labels: bug
