### ISSUE TITLE
Entities are not decoded

### ISSUE THREAD

**Issue by richfelker** [Alir3z4/html2text#182] opened 2017-08-24 17:37 UTC
`echo 'foo &gt;' | html2text`

Result: `foo &gt;`
Expected: `foo >`

This rather defeats any hope of using html2text for the main purpose I want it for, as a mailcap filter for reading html email and formatting it nicely to reply to (via mutt).

I'm not sure what should happen when the > is at beginning of line (where it would be ambiguous with md formatting) but it should probably be escaped, not left as an html entity (in which case I would just post-process the output to remove the escaping). Same applies to other non-ambiguous entities which might make better examples.

**Comment by andreskrey** [comment] 2017-10-03 18:05
Could not reproduce:

>>> import html2text
>>> 
>>> h = html2text.HTML2Text()
>>> print(h.handle("foo &gt;"))

foo >

Using [this revision](https://github.com/Alir3z4/html2text/commit/1317a98e2d47043f521e84d7c4ac79e821f6ab57)

**Comment by richfelker** [comment] 2017-10-03 19:07
I used the version available via pip (2016.9.19), so perhaps the bug has been fixed since then?

**Comment by andreskrey** [comment] 2017-10-03 21:51
I'm not familiar with the commits history but could be the reason.

**Comment by Alir3z4** [comment] 2017-10-04 06:25
I'm going to cut a release now which includes the the fixes now.

**Comment by Alir3z4** [comment] 2017-10-04 07:07
@andreskrey thanks for the confirmation and testing the issue on the latest.
@richfelker thanks for reporting the bug.

This has been fixed in the latest release.
The new version is available at https://pypi.python.org/pypi/html2text/2017.10.4

**Closed by Alir3z4** 2017-10-04 07:07 UTC
Labels: bug
